project:
  type: website
  render:
    - index.qmd
    - users/percyfal/index.qmd
    - users/percyfal/simulation/index.qmd
institute: NBIS
from: markdown+emoji
format:
  revealjs:
    toc: true
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: false
    footer: GARG
    smaller: true
    highlight-style: gruvbox
    fig-height: 12
    fig-width: 10
    fig-align: center
    text-align: center
    width: 1050
    height: 700
    margin: 0.05
    navigation-mode: vertical
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
execute:
  echo: true
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true
  freeze: auto
